### ISSUE TITLE
What is the current status of car-mirror?

### ISSUE THREAD

**Issue by gotjoshua** [fission-codes/car-mirror#90]
It is October, and i don't see movement on issues since Feb, and code since June.

Is this project an active priority for anyone? Any timeline or roadmap available for us eager consumers?

**Comment by matheus23** [comment]
Hello!
kubo-car-mirror will likely not see many updates in the immediate future.
We'll be building on top of https://github.com/fission-codes/rs-car-mirror/ instead!
That'll just enable us to make car mirror requests easier from browsers (with Wasm) and any rust CLIs we'd write in the future. (It makes it easier for our needs at fission. We didn't receive any funding for go-car-mirror work, so that's why we're focusing on mostly our needs.)

Also of note is that rs-car-mirror and go-car-mirror are not compatible at the moment. Neither are completely spec-adhering, (although [rs-car-mirror may be at some point](https://github.com/wnfs-wg/car-mirror-spec/pull/7)), and rs-car-mirror is just a lot simpler in terms of implementation & protocol.

---

Also of note: rs-car-mirror at the moment is mostly a bag of pure functions. It's not integrated with for example an HTTP library yet to turn car mirror protocol calls into HTTP requests & responses, and there's no Wasm bindings for now.
But it's definitely where development will continue.

**Comment by matheus23** [comment]
**Update**: [rs-car-mirror](https://github.com/fission-codes/rs-car-mirror/) is now released to crates.io and there exist libraries to use car mirror over HTTP & in Wasm, using car-mirror-reqwest and car-mirror-wasm.

For anyone interested in using car mirror with kubo, almost all necessary code to build a small webserver binary that exposes car mirror HTTP endpoints and talks to kubo as the blockstore exists out there, it just needs to be factored out, collected and packaged up.
